import { prisma } from '@/lib/prisma'

export const dynamic = 'force-dynamic'
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',notation:'compact',maximumFractionDigits:1}).format(n)
const num=(n:number)=>new Intl.NumberFormat('en-AU').format(n)
const tone:Record<string,string>={WON:'#00A7E2',LOST:'#EF3D55',PENDING:'#F99F38'}
function one(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value}

export default async function ForwardCalendarPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const params=await searchParams
  const all=await prisma.intelligenceDataset.findMany({where:{domain:'FORWARD_CALENDAR'},orderBy:{asOfLabel:'desc'}})
  const selected=one(params.dataset)||all.find(x=>x.id==='fc-intl-jan25')?.id||all[0]?.id
  const dataset=selected?await prisma.intelligenceDataset.findUnique({where:{id:selected},include:{forwardSummaries:{orderBy:{bidStatus:'asc'}},reasons:{orderBy:[{bidStatus:'asc'},{share:'desc'}]}}}):null
  if(!dataset)return <div className="p-8 text-gray-500">Run the intelligence scenario seed to load the Forward Calendar.</div>
  const validation=(dataset.validationSummary||{}) as Record<string,unknown>
  const maxReason=Math.max(1,...dataset.reasons.map(r=>r.share))
  return <div className="p-8">
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-wide text-orange-600">Bureaux intelligence</div><h1 className="mt-2 text-3xl font-black" style={{color:'#052460'}}>Forward Calendar</h1><p className="mt-2 text-sm text-gray-500">Live scenario reporting from versioned won, lost and pipeline snapshots.</p></div><form><select name="dataset" defaultValue={dataset.id} className="rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm" onChange={undefined}>{all.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="ml-2 rounded-xl bg-[#052460] px-4 py-3 text-sm font-bold text-white">Load</button></form></div>
    <div className={`mb-6 rounded-xl border p-4 text-sm ${String(validation.reportReconciliation).startsWith('PASSED')?'border-green-200 bg-green-50 text-green-800':'border-orange-200 bg-orange-50 text-orange-800'}`}><strong>Reconciliation: {String(validation.reportReconciliation||'not recorded').replaceAll('_',' ')}</strong>{validation.warning?<span> · {String(validation.warning)}</span>:null}<div className="mt-1 text-xs opacity-70">Source: {dataset.sourceFilename} · {dataset.rowCount} detailed rows · {dataset.asOfLabel}</div></div>
    <div className="mb-8 grid gap-4 md:grid-cols-3">{dataset.forwardSummaries.map(s=><section key={s.id} className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><div className="mb-4 flex items-center justify-between"><span className="rounded-full px-3 py-1 text-xs font-black text-white" style={{background:tone[s.bidStatus]||'#052460'}}>{s.bidStatus}</span><span className="text-xs text-gray-400">{dataset.market}</span></div><div className="text-4xl font-black" style={{color:'#052460'}}>{num(s.eventCount)}</div><div className="text-xs text-gray-400">business events</div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><strong>{num(s.totalDelegates)}</strong><div className="text-xs text-gray-400">delegates</div></div><div><strong>{num(s.totalDays)}</strong><div className="text-xs text-gray-400">delegate days</div></div><div><strong>{num(s.internationalDelegates)}</strong><div className="text-xs text-gray-400">international</div></div><div><strong>{money(s.totalSpend)}</strong><div className="text-xs text-gray-400">delegate spend</div></div></div></section>)}</div>
    <div className="grid gap-6 xl:grid-cols-2">{['WON','LOST'].map(status=>{const rows=dataset.reasons.filter(r=>r.bidStatus===status);return <section key={status} className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><div className="mb-5"><h2 className="font-black text-gray-900">Top reasons for bids {status.toLowerCase()}</h2><p className="mt-1 text-xs text-gray-500">Fractionally weighted where multiple reasons were recorded · response base n={rows[0]?.responseBase||0}</p></div><div className="space-y-4">{rows.map(r=><div key={r.id}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="text-gray-600">{r.reason}</span><strong>{r.share.toFixed(1)}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full" style={{width:`${r.share/maxReason*100}%`,background:tone[status]}}/></div></div>)}</div></section>})}</div>
    <div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50 p-5 text-xs leading-6 text-blue-800"><strong>Interpretation guardrail:</strong> snapshots overlap and are not flows. Changes between reports require stable bid/event IDs before they can be described as newly won, lost, added or removed. Reason percentages must always display response coverage.</div>
  </div>
}
