import { prisma } from '@/lib/prisma'

export const dynamic='force-dynamic'
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',notation:'compact',maximumFractionDigits:2}).format(n)
const pct=(a:number,b:number)=>b?`${(a/b*100).toFixed(1)}%`:'—'

export default async function EventCommercialsPage(){
 const [shows,events,datasets]=await Promise.all([prisma.commercialEvent.findMany({where:{datasetId:'commercial-eight-shows'},orderBy:{label:'asc'}}),prisma.commercialEvent.findMany({where:{datasetId:'commercial-three-events'},orderBy:{label:'asc'}}),prisma.intelligenceDataset.findMany({where:{domain:'COMMERCIAL'}})])
 const revenue=shows.reduce((s,x)=>s+(x.totalRevenue||0),0),expenses=shows.reduce((s,x)=>s+(x.directExpenses||0),0),profit=shows.reduce((s,x)=>s+(x.grossProfit||0),0)
 return <div className="p-8"><div className="mb-8"><div className="text-xs font-bold uppercase tracking-wide text-orange-600">Event performance</div><h1 className="mt-2 text-3xl font-black" style={{color:'#052460'}}>Commercial Explorer</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-500">De-identified scenario analysis. Known revenue/cost categories are shown without inventing missing registration revenue, overhead or floor-area yield.</p></div>
 <div className="mb-8 grid gap-4 md:grid-cols-4">{[['Portfolio revenue',money(revenue)],['Direct expenses',money(expenses)],['Gross contribution',money(profit)],['Portfolio margin',pct(profit,revenue)]].map(([l,v])=><div key={l} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="text-xs font-bold uppercase text-gray-400">{l}</div><div className="mt-2 text-3xl font-black" style={{color:'#052460'}}>{v}</div></div>)}</div>
 <section className="mb-8 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Eight-show cost and contribution comparison</h2><p className="mt-1 text-xs text-gray-500">Gross contribution is revenue less the supplied direct expense categories only.</p></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b bg-gray-50">{['Show','Revenue','Direct expenses','Gross contribution','Margin','Operations %','Marketing %'].map(x=><th key={x} className="px-5 py-3 text-left text-xs font-bold uppercase text-gray-500">{x}</th>)}</tr></thead><tbody>{shows.map(x=><tr key={x.id} className="border-b last:border-0"><td className="px-5 py-4 font-bold">{x.label}</td><td className="px-5 py-4 text-sm">{money(x.totalRevenue||0)}</td><td className="px-5 py-4 text-sm">{money(x.directExpenses||0)}</td><td className="px-5 py-4 text-sm font-bold">{money(x.grossProfit||0)}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${(x.grossProfit||0)/(x.totalRevenue||1)>=.5?'bg-green-100 text-green-700':'bg-orange-100 text-orange-700'}`}>{pct(x.grossProfit||0,x.totalRevenue||0)}</span></td><td className="px-5 py-4 text-sm">{pct(x.operationsSpend||0,x.totalRevenue||0)}</td><td className="px-5 py-4 text-sm">{pct(x.marketingSpend||0,x.totalRevenue||0)}</td></tr>)}</tbody></table></div></section>
 <div className="grid gap-5 xl:grid-cols-3">{events.map(x=>{const costs=(x.venueSpend||0)+(x.cateringSpend||0)+(x.marketingSpend||0);const knownRevenue=(x.sponsorshipRevenue||0)+(x.exhibitionRevenue||0);return <article key={x.id} className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold uppercase text-orange-600">{x.eventType} · {x.industry}</div><h2 className="mt-1 text-xl font-black" style={{color:'#052460'}}>{x.label}</h2></div><span className="text-xs text-gray-400">{x.marketPositioning}</span></div><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><strong>{x.registrations}</strong><div className="text-xs text-gray-400">registrations</div></div><div><strong>{money(costs/(x.registrations||1))}</strong><div className="text-xs text-gray-400">known cost / reg</div></div><div><strong>{pct(x.interstateRegistrations||0,x.registrations||0)}</strong><div className="text-xs text-gray-400">interstate</div></div><div><strong>{pct(x.internationalRegistrations||0,x.registrations||0)}</strong><div className="text-xs text-gray-400">international</div></div><div><strong>{money(x.exhibitionRevenue||0)}</strong><div className="text-xs text-gray-400">exhibition revenue</div></div><div><strong>{x.sponsorshipRevenue==null?'Missing':money(x.sponsorshipRevenue)}</strong><div className="text-xs text-gray-400">sponsorship</div></div></div><div className={`mt-5 rounded-xl p-3 text-xs ${knownRevenue>=costs?'bg-green-50 text-green-700':'bg-orange-50 text-orange-700'}`}>Known revenue less supplied costs: {money(knownRevenue-costs)}. This is not profit because revenue/cost categories are incomplete.</div></article>})}</div>
 <div className="mt-6 text-xs text-gray-400">Sources: {datasets.map(x=>x.sourceFilename).join(' · ')}</div></div>
}
