import { prisma } from '@/lib/prisma'

export const dynamic='force-dynamic'
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',notation:'compact',maximumFractionDigits:1}).format(n)

export default async function BidPipelinePage(){
 const dataset=await prisma.intelligenceDataset.findUnique({where:{id:'bid-dummy-pilot'},include:{bidRecords:{orderBy:{existingWinPct:'desc'}}}})
 if(!dataset)return <div className="p-8 text-gray-500">Run the intelligence scenario seed to load the bid pilot.</div>
 const meta=(dataset.validationSummary||{}) as Record<string,number|string>
 const value=dataset.bidRecords.reduce((s,x)=>s+(x.economicValue||0),0)
 return <div className="p-8"><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-wide text-sky-600">Synthetic workflow prototype</div><h1 className="mt-2 text-3xl font-black" style={{color:'#052460'}}>Bid Pipeline</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-500">Prospect triage using supplied dummy data. Existing percentages are displayed as source values—not ABEA-NDH predictions.</p></div><span className="rounded-full bg-red-100 px-4 py-2 text-xs font-black text-red-700">NOT FOR PREDICTIVE USE</span></div>
 <div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><strong>Model gate failed:</strong> only {String(meta.historicalOutcomes)} synthetic outcomes ({String(meta.won)} won / {String(meta.lost)} lost), {String(meta.dateSequenceIssues)} date-sequence issues, and the existing score averages {String(meta.existingScoreWonAverage)}% for wins versus {String(meta.existingScoreLostAverage)}% for losses.</div>
 <div className="mb-8 grid gap-4 md:grid-cols-4">{[['Prospects in preview',dataset.bidRecords.length],['Source prospects',meta.prospects],['Preview economic value',money(value)],['Source rows',dataset.rowCount]].map(([l,v])=><div key={l} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="text-xs font-bold uppercase text-gray-400">{l}</div><div className="mt-2 text-3xl font-black" style={{color:'#052460'}}>{v}</div></div>)}</div>
 <div className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Prospect review queue</h2><p className="mt-1 text-xs text-gray-500">Ten-row preview from the 100 supplied synthetic prospects. Priority remains human-owned.</p></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b bg-gray-50">{['Lead','Event','Sector','Delegates','Economic value','Source FC %','Host / resources','Competition','Strategic value'].map(x=><th key={x} className="px-4 py-3 text-left text-xs font-bold uppercase text-gray-500">{x}</th>)}</tr></thead><tbody>{dataset.bidRecords.map(x=><tr key={x.id} className="border-b last:border-0"><td className="px-4 py-4 font-mono text-xs font-bold">{x.leadId}</td><td className="px-4 py-4 text-sm font-semibold">{x.eventType}<div className="text-xs font-normal text-gray-400">{x.venue}</div></td><td className="px-4 py-4 text-xs">{x.economicSector}<div className="text-gray-400">{x.prioritySector}</div></td><td className="px-4 py-4 text-sm">{x.delegates?.toLocaleString()}</td><td className="px-4 py-4 text-sm">{money(x.economicValue||0)}</td><td className="px-4 py-4"><span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-bold text-gray-600">{x.existingWinPct}%</span></td><td className="px-4 py-4 text-xs">{x.localHostStrength} / {x.bidResources}</td><td className="px-4 py-4 text-xs">{x.competitorCount} competitors</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${x.strategicValue==='High'?'bg-green-100 text-green-700':'bg-yellow-100 text-yellow-700'}`}>{x.strategicValue}</span></td></tr>)}</tbody></table></div></div>
 <div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50 p-5 text-xs leading-6 text-blue-800"><strong>Next evidence gate:</strong> onboard authentic outcomes with decision-time features only, exclude post-outcome reasons/dates, reconcile competitor fields, validate chronologically, calibrate probabilities and record human overrides. Until then this remains a workflow and descriptive-analysis prototype.</div></div>
}
